import com.ryanjin.example.Application;
import org.apache.tomcat.jni.Library;
import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'donghyunjin' at '16. 4. 4 오후 7:03' with Gradle 2.8
 *
 * @author donghyunjin, @date 16. 4. 4 오후 7:03
 */
public class ApplicationTest {
    @Test public void testSomeLibraryMethod() {
        Application classUnderTest = new Application();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
