package com.ryanjin.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'donghyunjin' at '16. 4. 4 오후 7:03' with Gradle 2.8
 *
 * @author donghyunjin, @date 16. 4. 4 오후 7:03
 */
@SpringBootApplication
@EnableAutoConfiguration
public class Application {
    public static void main(String[] args) throws Exception {
        SpringApplication.run(Application.class, args);
    }
}
